### ISSUE TITLE
[Bug Report]: There is no tracked object with id '313'

### ISSUE THREAD

**Issue by wisamidris7** [masastack/MASA.Blazor#1503]
### Masa.Blazor version

lastest

## This Problem Showed In WebAssembly And Server When Clicking Fast
Like I Clicked But And I Clicked Other
![Screenshot 2023-08-28 035352](https://github.com/masastack/MASA.Blazor/assets/104096256/54e070f5-2805-4aff-8aa3-513f47256e86)

blazor.server.js:1  Uncaught (in promise) Error: System.ArgumentException: There is no tracked object with id '313'. Perhaps the DotNetObjectReference instance was already disposed. (Parameter 'dotNetObjectId')
   at Microsoft.JSInterop.JSRuntime.GetObjectReference(Int64 dotNetObjectId)
   at Microsoft.JSInterop.Infrastructure.DotNetDispatcher.BeginInvokeDotNet(JSRuntime jsRuntime, DotNetInvocationInfo invocationInfo, String argsJson)
    at Ft.endInvokeDotNetFromJS (blazor.server.js:1:3718)
    at Ft._invokeClientMethod (blazor.server.js:1:75072)
    at Ft._processIncomingData (blazor.server.js:1:72696)
    at Ft.connection.onreceive (blazor.server.js:1:67009)
    at i.onmessage (blazor.server.js:1:51322)
endInvokeDotNetFromJS @ blazor.server.js:1
_invokeClientMethod @ blazor.server.js:1
_processIncomingData @ blazor.server.js:1
Ft.connection.onreceive @ blazor.server.js:1
i.onmessage @ blazor.server.js:1

**Comment by capdiem** [comment]
@wisamidris7 Clicking on ListItem on Nav to change page?

**Comment by wisamidris7** [comment]
yes

**Comment by wisamidris7** [comment]
i solved problem

**Comment by pramodIfx** [comment]
How?
