### ISSUE TITLE
[Bug Report]: Masa.Blazor.ResizeJSModule.UnobserveAsync大量报错，前端没有异常，但是后台依然大量的报错

### ISSUE THREAD

**Issue by bloodxia** [masastack/MASA.Blazor#1632]
### Masa.Blazor version

1.1.1

### Describe the bug

```
 warn: Microsoft.AspNetCore.Components.Server.Circuits.RemoteRenderer[100]
       Unhandled exception rendering component: A task was canceled.
       System.Threading.Tasks.TaskCanceledException: A task was canceled.
          at Microsoft.JSInterop.JSRuntime.InvokeAsync[TValue](Int64 targetInstanceId, String identifier, Object[] args)
          at BlazorComponent.JSInterop.JSModule.InvokeVoidAsync(String identifier, Object[] args)
          at Masa.Blazor.ResizeJSModule.UnobserveAsync(ElementReference el)
          at BlazorComponent.BSlideGroup.System.IAsyncDisposable.DisposeAsync()
          at Microsoft.AspNetCore.Components.RenderTree.Renderer.<>c__DisplayClass74_0.<<Dispose>g__HandleAsyncExceptions|1>d.MoveNext()
 warn: Microsoft.AspNetCore.Components.Server.Circuits.RemoteRenderer[100]
       Unhandled exception rendering component: A task was canceled.
       System.Threading.Tasks.TaskCanceledException: A task was canceled.
          at Microsoft.JSInterop.JSRuntime.InvokeAsync[TValue](Int64 targetInstanceId, String identifier, Object[] args)
          at BlazorComponent.JSInterop.JSModule.InvokeVoidAsync(String identifier, Object[] args)
          at Masa.Blazor.ResizeJSModule.UnobserveAsync(ElementReference el)
          at BlazorComponent.BSlideGroup.System.IAsyncDisposable.DisposeAsync()
          at Microsoft.AspNetCore.Components.RenderTree.Renderer.<>c__DisplayClass74_0.<<Dispose>g__HandleAsyncExceptions|1>d.MoveNext()
 fail: Microsoft.AspNetCore.Components.Server.Circuits.CircuitHost[111]
       Unhandled exception in circuit 'QeYKNn9GCgcXqn3iPOPtfedJcmejQffrRvqyjq7v8rk'.
       System.AggregateException: Exceptions were encountered while disposing components. (A task was canceled.) (A task was canceled.)
        ---> System.Threading.Tasks.TaskCanceledException: A task was canceled.
          at Microsoft.JSInterop.JSRuntime.InvokeAsync[TValue](Int64 targetInstanceId, String identifier, Object[] args)
          at BlazorComponent.JSInterop.JSModule.InvokeVoidAsync(String identifier, Object[] args)
          at Masa.Blazor.ResizeJSModule.UnobserveAsync(ElementReference el)
          at BlazorComponent.BSlideGroup.System.IAsyncDisposable.DisposeAsync()
          at Microsoft.AspNetCore.Components.RenderTree.Renderer.<>c__DisplayClass74_0.<<Dispose>g__HandleAsyncExceptions|1>d.MoveNext()
          --- End of inner exception stack trace ---
```

**Comment by bloodxia** [comment]
https://github.com/masastack/MASA.Blazor/blob/a8100d3aa7cebe552f15a5c593b87440f36a5573/src/Masa.Blazor/JSModules/ResizeObserver/ResizeJSModule.cs#L14
这个和昨天的descriptions的错误类似，只要在这里加个try catch就可以了
