### ISSUE TITLE
[Bug Report]: MEditorUpload上传图片返回格式

### ISSUE THREAD

**Issue by kx500** [masastack/MASA.Blazor#2193]
private MEditorUpload _upload = new MEditorUpload
{
    Action = "/api/upload/image",//Please change your upload address
};

Action  所设的地址应该返回什么格式和哪些参数

**Comment by kx500** [comment]
fail: Microsoft.AspNetCore.Components.Server.Circuits.CircuitHost[111]
      Unhandled exception in circuit 'XQbHZ2plAw4FOnwX1I3QQzZlZinj4HO30zXmtG2PAUk'.
      Microsoft.JSInterop.JSException: moduleClass is not a constructor
TypeError: moduleClass is not a constructor
    at SnowTheme.addModule (https://cdn.masastack.com/npm/quill/1.3.6/quill.js:6057:28)
    at SnowTheme.addModule (https://cdn.masastack.com/npm/quill/1.3.6/quill.js:6701:121)
    at https://cdn.masastack.com/npm/quill/1.3.6/quill.js:6049:17
    at Array.forEach (<anonymous>)
    at SnowTheme.init (https://cdn.masastack.com/npm/quill/1.3.6/quill.js:6047:41)
    at new Quill (https://cdn.masastack.com/npm/quill/1.3.6/quill.js:1113:16)
    at Module.init (http://192.168.241.67:5276/_content/Masa.Blazor/js/quill/quill-helper.js:60:20)
    at http://192.168.241.67:5276/_framework/blazor.web.js:1:3047
    at new Promise (<anonymous>)
    at y.beginInvokeJSFromDotNet (http://192.168.241.67:5276/_framework/blazor.web.js:1:3004)
         at Microsoft.JSInterop.JSRuntime.InvokeAsync[TValue](Int64 targetInstanceId, String identifier, Object[] args)
         at Microsoft.JSInterop.JSObjectReferenceExtensions.InvokeVoidAsync(IJSObjectReference jsObjectReference, String identifier, Object[] args)
         at Masa.Blazor.MEditor.CreateEditorAsync()
         at Masa.Blazor.MEditor.OnAfterRenderAsync(Boolean firstRender)
         at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle, ComponentState owningComponentState)
warn: Microsoft.AspNetCore.Components.Server.Circuits.RemoteRenderer[100]
      Unhandled exception rendering component: JavaScript interop calls cannot be issued at this time. This is because the circuit has disconnected and is being disposed.
      Microsoft.JSInterop.JSDisconnectedException: JavaScript interop calls cannot be issued at this time. This is because the circuit has disconnected and is being disposed.
         at Microsoft.AspNetCore.Components.Server.Circuits.RemoteJSRuntime.BeginInvokeJS(Int64 asyncHandle, String identifier, String argsJson, JSCallResultType resultType, Int64 targetInstanceId)
         at Microsoft.JSInterop.JSRuntime.InvokeAsync[TValue](Int64 targetInstanceId, String identifier, CancellationToken cancellationToken, Object[] args)
         at Microsoft.JSInterop.JSRuntime.InvokeAsync[TValue](Int64 targetInstanceId, String identifier, Object[] args)
         at Masa.Blazor.Extensions.JsRuntimeExtensions.GetNumberPropAsync(IJSRuntime jsRuntime, Object el, String name)
         at Masa.Blazor.MTextField`1.SetLabelWidthAsync()
         at Masa.Blazor.MTextField`1.OnAfterRenderAsync(Boolean firstRender)
         at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle, ComponentState owningComponentState)
